services:
  - type: web
    name: aerofisc-backend
    runtime: docker
    repo: https://github.com/Satya136-dvsn/Aerofisc
    rootDir: backend
    plan: free
    region: oregon
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://db.jbfqrfjswygcagvhtxcs.supabase.co:5432/postgres
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false # User will input this securely in dashboard
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ALLOWED_ORIGINS
        value: "*" # Update this after dealing with frontend
      - key: GEMINI_API_KEY
        sync: false
      - key: ALPHAVANTAGE_API_KEY
        sync: false
      - key: PORT
        value: 8080

version: "1"
